# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET-build-development

on:
  pull_request:
    branches: [ "development" ]



jobs:
  build:
    permissions: write-all
    runs-on: windows-latest
    env:
      BRANCH_NAME: ${{ github.head_ref }} 
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release -p:Platform=x86 --output ./bin/
    - name: copy prefabs
      run: cp "./Resources/prefabs" "./bin" -r
    - name: Write build time
      run: date +"%Y-%m-%d %H:%M" > ./bin/build
    - name: Create Zip File
      uses: vimtor/action-zip@v1.1
      with:
        files: ./bin/
        dest: ./HammerTime.zip
    - name: Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
            ./HammerTime.zip
            ./Hammertime.Editor.2.0.7.2.exe
        automatic_release_tag: latest-${{env.BRANCH_NAME}}
